/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_PB_TELEMETRY_PB_H_INCLUDED
#define PB_PB_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _pb_TelemetryEvent { 
    int32_t timestamp; 
    float us_front; 
    float us_left; 
    float us_back; 
    float accel_x; 
    float accel_y; 
    float accel_z; 
    float gyro_x; 
    float gyro_y; 
    float gyro_z; 
} pb_TelemetryEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define pb_TelemetryEvent_init_default           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define pb_TelemetryEvent_init_zero              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define pb_TelemetryEvent_timestamp_tag          1
#define pb_TelemetryEvent_us_front_tag           2
#define pb_TelemetryEvent_us_left_tag            3
#define pb_TelemetryEvent_us_back_tag            4
#define pb_TelemetryEvent_accel_x_tag            5
#define pb_TelemetryEvent_accel_y_tag            6
#define pb_TelemetryEvent_accel_z_tag            7
#define pb_TelemetryEvent_gyro_x_tag             8
#define pb_TelemetryEvent_gyro_y_tag             9
#define pb_TelemetryEvent_gyro_z_tag             10

/* Struct field encoding specification for nanopb */
#define pb_TelemetryEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    timestamp,         1) \
X(a, STATIC,   SINGULAR, FLOAT,    us_front,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    us_left,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    us_back,           4) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_x,           5) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_y,           6) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_z,           7) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_x,            8) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_y,            9) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_z,           10)
#define pb_TelemetryEvent_CALLBACK NULL
#define pb_TelemetryEvent_DEFAULT NULL

extern const pb_msgdesc_t pb_TelemetryEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pb_TelemetryEvent_fields &pb_TelemetryEvent_msg

/* Maximum encoded size of messages (where known) */
#define pb_TelemetryEvent_size                   56

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
